### ISSUE TITLE
Adding 0's after the "fractionDigits" limit doesn't trigger formatting

### ISSUE THREAD

**Issue by fmaclen** [Canutin/svelte-currency-input#30]
- `$1.2211111111` > `$1.22` ❤️ 
- `$1.2200000000` > `$1.2200000000` 💔

**Comment by gokullan** [comment]
Hi, there! I would like to take up this issue. Can it be assigned to me?

**Comment by fmaclen** [comment]
@gokullan sounds good, submit a PR when you are ready.
Thanks!
