### ISSUE TITLE
Apply formatting on:blur event

### ISSUE THREAD

**Issue by fmaclen** [Canutin/svelte-currency-input#33]
When the user clicks away from the field, we should run `setFormattedValue()` to apply the formatting one last time.

**Comment by gokullan** [comment]
Hi, there! I have a question. When the user clicks away from the field, `value` doesn't change, correct? So why do we need to call `setFormattedValue()`?

**Comment by fmaclen** [comment]
@gokullan there are some scenarios where formatting is not automatically applied, more specifically:
- When pressing `Backspace` and the [`formattedValue` is `['$', '-$', "-"]`](https://github.com/Canutin/svelte-currency-input/blob/3d383f1780b5802ee5d66ddef002c182f9f1963b/src/lib/CurrencyInput.svelte#L62-L65)
- When the decimal point is `.` and you type [`123.` but don't enter decimals](https://github.com/Canutin/svelte-currency-input/blob/3d383f1780b5802ee5d66ddef002c182f9f1963b/src/lib/CurrencyInput.svelte#L51-L52) (same if  `,` decimal point)

In these cases, if you click away from the input it will just stay unformatted.

It'd be nice if the `on:blur` event applied the formatting, which for the cases above would end up looking like:
- `$0.00`
- `$123`
